config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"

  resources :recipes, only: %i[index show] do
    collection do
      get :search
    end

    member do
      get :check_inventory
    end
  end

  resources :save_files, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :player
  belongs_to :ingredient
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def search
    if params[:recipe_search].present?
      query = "%#{params[:recipe_search].downcase}%"
      @recipes = Recipe.where("LOWER(name) ILIKE ?", query)
    else
      @recipes = Recipe.all
    end

    respond_to do |format|
      format.turbo_stream { render partial: "recipes/results", locals: { recipes: @recipes } }
      format.html { render "index" }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StardewPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_results.html.erb
<div id="results">
  <% if @recipes.any? %>
    <ul>
      <% @recipes.each do |recipe| %>
        <li>
          <%= recipe.name %>
        </li>
      <% end %>
    </ul>
  <%# <% else %>
    <%# <p>No results found.</p> %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<%= form_with url: search_recipes_path, method: :get, data: { turbo_frame: "results"} do |form| %>
  <%= form.search_field :recipe_search, placeholder: "Item search", oninput: "this.form.requestSubmit()" %>
  <%= form.submit "Search", style: "display: none;" %>
<% end %>

<turbo-frame id="results">
  <%= render "recipes/results", recipes: @recipes %>
</turbo-frame>